JSON = 'application/json'
VALID_EMAIL = 'bla@bla.com'
VALID_PASSWORD = '12345'
SHORT_NAME = 'test'
FULL_NAME = 'test test'
LIVE_TOKEN = 'qwertyuiop123456'
EXPIRED_TOKEN = '123456qwertyuiop'
NONEXISTENT_TOKEN = 'asdfghjklzxcvbnm'
